Add controllers
DmitryMisevra/java-shareit pull request #1
Opened 2023-11-20 17:11 UTC by DmitryMisevra

2023-11-21 19:55 UTC, kriwsha requested changes

2023-11-21 19:55 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemMapper itemMapper;
Логику маппинга я бы рекомендовал убрать в сервис, чтобы не загромождать контроллер. Вся бизнес-логика должна оставаться в сервисах.

2023-11-21 19:55 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final UserMapper userMapper;
И здесь та же рекомендация - разделить логику сервиса и контроллера

2023-11-22 15:26 UTC, DmitryMisevra commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemMapper itemMapper;
Готово!

2023-11-22 15:26 UTC, DmitryMisevra commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final UserMapper userMapper;
Готово!

2023-11-23 12:44 UTC, kriwsha approved these changes

2023-11-30 08:37 UTC, merged